services:
#    geo.sync.continents:
#        class: GeonamesBundle\Command\GeonamesSyncContinentsCommand
#        tags:
#            -  { name: console.command }
#    geo.sync.countries:
#        class: GeonamesBundle\Command\GeonamesSyncCountriesCommand
#        tags:
#            -  { name: console.command }